// Code generated by protoc-gen-zig
///! package google.protobuf.compiler
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;
const json = protobuf.json;
const UnionDecodingError = protobuf.UnionDecodingError;
/// import package google.protobuf
const google_protobuf = @import("../protobuf.pb.zig");

pub const Version = struct {
    pb: protobuf.ProtobufMixins(@This()) = .{},
    major: ?i32 = null,
    minor: ?i32 = null,
    patch: ?i32 = null,
    suffix: ?ManagedString = null,

    pub const _desc_table = .{
        .major = fd(1, null, .{ .Varint = .Simple }),
        .minor = fd(2, null, .{ .Varint = .Simple }),
        .patch = fd(3, null, .{ .Varint = .Simple }),
        .suffix = fd(4, null, .String),
    };
};

pub const CodeGeneratorRequest = struct {
    pb: protobuf.ProtobufMixins(@This()) = .{},
    file_to_generate: ArrayList(ManagedString) = .empty,
    parameter: ?ManagedString = null,
    proto_file: ArrayList(google_protobuf.FileDescriptorProto) = .empty,
    compiler_version: ?Version = null,

    pub const _desc_table = .{
        .file_to_generate = fd(1, null, .{ .List = .String }),
        .parameter = fd(2, null, .String),
        .proto_file = fd(15, null, .{ .List = .{ .SubMessage = {} } }),
        .compiler_version = fd(3, null, .{ .SubMessage = {} }),
    };
};

pub const CodeGeneratorResponse = struct {
    pb: protobuf.ProtobufMixins(@This()) = .{},
    @"error": ?ManagedString = null,
    supported_features: ?u64 = null,
    file: ArrayList(CodeGeneratorResponse.File) = .empty,

    pub const _desc_table = .{
        .@"error" = fd(1, null, .String),
        .supported_features = fd(2, null, .{ .Varint = .Simple }),
        .file = fd(15, null, .{ .List = .{ .SubMessage = {} } }),
    };

    pub const Feature = enum(i32) {
        FEATURE_NONE = 0,
        FEATURE_PROTO3_OPTIONAL = 1,
        _,
    };

    pub const File = struct {
        pb: protobuf.ProtobufMixins(@This()) = .{},
        name: ?ManagedString = null,
        insertion_point: ?ManagedString = null,
        content: ?ManagedString = null,
        generated_code_info: ?google_protobuf.GeneratedCodeInfo = null,

        pub const _desc_table = .{
            .name = fd(1, null, .String),
            .insertion_point = fd(2, null, .String),
            .content = fd(15, null, .String),
            .generated_code_info = fd(16, null, .{ .SubMessage = {} }),
        };
    };
};
